export const MERCHANT_CATEGORY_MAP: Map<string, string> = new Map([
  ['grab', 'Di chuyển'],
  ['be', 'Di chuyển'],
  ['goviet', 'Di chuyển'],
  ['xanh sm', 'Di chuyển'],
  ['mai linh', 'Di chuyển'],
  ['taxi', 'Di chuyển'],
  ['xăng', 'Di chuyển'],
  ['petrol', 'Di chuyển'],
  ['shell', 'Di chuyển'],
  ['caltex', 'Di chuyển'],
  ['cheedo', 'Di chuyển'],
  ['cà phê', 'Ăn uống'],
  ['cafe', 'Ăn uống'],
  ['coffee', 'Ăn uống'],
  [' Highlands', 'Ăn uống'],
  ['starbucks', 'Ăn uống'],
  ['phở', 'Ăn uống'],
  ['bún', 'Ăn uống'],
  ['cơm', 'Ăn uống'],
  ['bánh mì', 'Ăn uống'],
  ['mì', 'Ăn uống'],
  ['trà sữa', 'Ăn uống'],
  [' Highlands Coffee', 'Ăn uống'],
  ['KFC', 'Ăn uống'],
  ['McDonalds', 'Ăn uống'],
  ['Jollibee', 'Ăn uống'],
  ['Pizza', 'Ăn uống'],
  ['Burger King', 'Ăn uống'],
  ['Lotteria', 'Ăn uống'],
  ['Masan', 'Ăn uống'],
  ['Winmart', 'Ăn uống'],
  ['Co.opmart', 'Ăn uống'],
  ['AEON', 'Mua sắm'],
  ['Lotte', 'Mua sắm'],
  ['BigC', 'Mua sắm'],
  ['Vinmart', 'Mua sắm'],
  ['Shopee', 'Mua sắm'],
  ['Lazada', 'Mua sắm'],
  ['TikTok Shop', 'Mua sắm'],
  ['Tiki', 'Mua sắm'],
  ['Netflix', 'Giải trí'],
  ['Spotify', 'Giải trí'],
  ['YouTube', 'Giải trí'],
  ['Disney+', 'Giải trí'],
  ['Zalo', 'Giải trí'],
  ['Facebook', 'Giải trí'],
  ['TikTok', 'Giải trí'],
  ['Game', 'Giải trí'],
  ['Apple', 'Mua sắm'],
  ['Samsung', 'Mua sắm'],
  ['OPPO', 'Mua sắm'],
  ['Xiaomi', 'Mua sắm'],
  ['Viettel', 'Hóa đơn'],
  ['Mobifone', 'Hóa đơn'],
  ['Vinaphone', 'Hóa đơn'],
  ['Vietnamobile', 'Hóa đơn'],
  ['FPT', 'Hóa đơn'],
  ['VNPT', 'Hóa đơn'],
  ['internet', 'Hóa đơn'],
  ['điện', 'Hóa đơn'],
  ['nước', 'Hóa đơn'],
  ['gas', 'Hóa đơn'],
  ['bảo hiểm', 'Hóa đơn'],
  ['nhà thuốc', 'Sức khỏe'],
  ['phòng khám', 'Sức khỏe'],
  ['bệnh viện', 'Sức khỏe'],
  ['y tế', 'Sức khỏe'],
  ['thuốc', 'Sức khỏe'],
  ['vitamin', 'Sức khỏe'],
  ['sách', 'Giáo dục'],
  ['khóa học', 'Giáo dục'],
  ['coursera', 'Giáo dục'],
  ['udemy', 'Giáo dục'],
]);
